### ISSUE TITLE
Feature Checklist

### ISSUE THREAD

**Issue by CorvusPrudens** [green-ogre/kingdom#1]
## Saturday
- [x] Insight
- [x] Days
- [x] 1 Character
- [x] Character sliding introduction
- [x] Heart Death

## Remaining core mechanics

- [x] Days
- [x] Unique events
- [x] Insight
- [x] Revolution
- [x] Death due to heart

## Remaining features

- [x] Character animations
- [ ] Crowd sentiment (occasional speech bubbles)
- [ ] Special spooky glitches for cosmic being
- [x] Introduction
- [x] Completion screen
- [ ] Main menu

## Remaining art

- [x] Character art
- [x] Insight ui
- [x] Loose ui
- [x] Win ui
- [x] Day one writing
- [ ] Day two writing
- [ ] Day three writing
- [x] Regular music
- [x] Spooky music
- [x] Intro/end music (?)
